version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: parts_badger
      POSTGRES_USER: parts_badger
      POSTGRES_PASSWORD: parts_badger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SECRET_KEY: dev-secret-key
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      POSTGRES_DB: parts_badger
      POSTGRES_USER: parts_badger
      POSTGRES_PASSWORD: parts_badger
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  worker:
    build:
      context: ./backend
    command: sh -c "celery -A config worker -l info"
    environment:
      DJANGO_SECRET_KEY: dev-secret-key
      DJANGO_DEBUG: "True"
      POSTGRES_DB: parts_badger
      POSTGRES_USER: parts_badger
      POSTGRES_PASSWORD: parts_badger
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - rabbitmq

volumes:
  pgdata:
